version: 2

dist: _output/dist

# build binaries
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
# build container images
dockers:
  - image_templates:
      - "cr.seqera.io/public/staticreg:{{.Tag}}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "cr.seqera.io/public/staticreg:{{.Tag}}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

# merge multi arch image manifests
docker_manifests:
  - name_template: "cr.seqera.io/public/staticreg:{{.Tag}}"
    image_templates:
      - "cr.seqera.io/public/staticreg:{{.Tag}}-amd64"
      - "cr.seqera.io/public/staticreg:{{.Tag}}-arm64"
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^release:"
      - "^chore:"
      - "^build:"
      - "^wip"
