name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: public.cr.seqera.io
          username: public-cr-admin
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            public.cr.seqera.io/seqeralabs/staticreg
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      # amd64
      - name: Build (amd64)
        run: sudo make clean && make GO="docker run -e GOARCH=amd64 -v $PWD:/staticreg -w /staticreg --rm $(cat .go_image) go"
      - name: Build image and push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # arm64
      - name: Build (arm64)
        run: sudo make clean && make GO="docker run -e GOARCH=arm64 -v $PWD:/staticreg -w /staticreg --rm $(cat .go_image) go"
      - name: Build image and push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
