name: Build

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          distribution: goreleaser
          install-only: true
      - name: Build snapshot
        run: make snapshot
      - name: Archive snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            _output/dist/*.tar.gz
            _output/dist/*.zip
            _output/dist/*.txt
            _output/dist/*.json
