name: Build

on:
  push:
    branches:
      - master
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: public.cr.seqera.io
          username: public-cr-admin
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: make GO="docker run -v $PWD:/staticreg -w /staticreg --rm $(cat .go_image) go"
      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: public.cr.seqera.io/seqeralabs/staticreg
