name: Build

on:
  push:
    branches:
      - master
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: public.cr.seqera.io
          username: public-cr-admin
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # amd64
      - name: Build (amd64)
        run: sudo make clean && make GO="docker run -e GOARCH=amd64 -v $PWD:/staticreg -w /staticreg --rm $(cat .go_image) go"
      - name: Build image and push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: public.cr.seqera.io/seqeralabs/staticreg
      # arm64
      - name: Build (arm64)
        run: sudo make clean && make GO="docker run -e GOARCH=arm64 -v $PWD:/staticreg -w /staticreg --rm $(cat .go_image) go"
      - name: Build (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: public.cr.seqera.io/seqeralabs/staticreg
