name: Build

on:
  push:
    branches:
      - master
    # tags:
    #   - "v*.*.*"
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: public.cr.seqera.io
          username: public-cr-admin
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build snapshot
        run: make snapshot
